# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_user_patient_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(482, 261)
        self.pushButton_user = QtWidgets.QPushButton(Dialog)
        self.pushButton_user.setGeometry(QtCore.QRect(0, 200, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_user.setFont(font)
        self.pushButton_user.setObjectName("pushButton_user")
        self.pushButton_exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(350, 190, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_fee = QtWidgets.QPushButton(Dialog)
        self.pushButton_fee.setGeometry(QtCore.QRect(0, 140, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_fee.setFont(font)
        self.pushButton_fee.setObjectName("pushButton_fee")
        self.pushButton_switch = QtWidgets.QPushButton(Dialog)
        self.pushButton_switch.setGeometry(QtCore.QRect(230, 190, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_switch.setFont(font)
        self.pushButton_switch.setObjectName("pushButton_switch")
        self.label_welcome = QtWidgets.QLabel(Dialog)
        self.label_welcome.setGeometry(QtCore.QRect(210, 40, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.label_help = QtWidgets.QLabel(Dialog)
        self.label_help.setGeometry(QtCore.QRect(210, 120, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_help.setFont(font)
        self.label_help.setAlignment(QtCore.Qt.AlignCenter)
        self.label_help.setObjectName("label_help")
        self.pushButton_register = QtWidgets.QPushButton(Dialog)
        self.pushButton_register.setGeometry(QtCore.QRect(0, 0, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_diagnosis = QtWidgets.QPushButton(Dialog)
        self.pushButton_diagnosis.setGeometry(QtCore.QRect(0, 70, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_diagnosis.setFont(font)
        self.pushButton_diagnosis.setObjectName("pushButton_diagnosis")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_user.setText(_translate("Dialog", "个人信息"))
        self.pushButton_exit.setText(_translate("Dialog", "退出程序"))
        self.pushButton_fee.setText(_translate("Dialog", "缴费"))
        self.pushButton_switch.setText(_translate("Dialog", "切换用户"))
        self.label_welcome.setText(_translate("Dialog", "欢迎"))
        self.label_help.setText(_translate("Dialog", "点击按钮进入各功能！"))
        self.pushButton_register.setText(_translate("Dialog", "预约挂号"))
        self.pushButton_diagnosis.setText(_translate("Dialog", "就诊记录"))
