# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_medicine_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 223)
        self.pushButton_godown_entry = QtWidgets.QPushButton(Dialog)
        self.pushButton_godown_entry.setGeometry(QtCore.QRect(0, 140, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_godown_entry.setFont(font)
        self.pushButton_godown_entry.setObjectName("pushButton_godown_entry")
        self.pushButton_godown_slave = QtWidgets.QPushButton(Dialog)
        self.pushButton_godown_slave.setGeometry(QtCore.QRect(0, 70, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_godown_slave.setFont(font)
        self.pushButton_godown_slave.setObjectName("pushButton_godown_slave")
        self.pushButton_medicine = QtWidgets.QPushButton(Dialog)
        self.pushButton_medicine.setGeometry(QtCore.QRect(0, 0, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_medicine.setFont(font)
        self.pushButton_medicine.setObjectName("pushButton_medicine")
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setGeometry(QtCore.QRect(250, 120, 200, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_welcome = QtWidgets.QLabel(Dialog)
        self.label_welcome.setGeometry(QtCore.QRect(250, 50, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_godown_entry.setText(_translate("Dialog", "药品入库主单"))
        self.pushButton_godown_slave.setText(_translate("Dialog", "药品入库从单"))
        self.pushButton_medicine.setText(_translate("Dialog", "药品"))
        self.pushButton_back.setText(_translate("Dialog", "返回"))
        self.label_welcome.setText(_translate("Dialog", "药房管理"))
