# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_diagnosis_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(478, 236)
        self.pushButton_diagnosis = QtWidgets.QPushButton(Dialog)
        self.pushButton_diagnosis.setGeometry(QtCore.QRect(0, 0, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_diagnosis.setFont(font)
        self.pushButton_diagnosis.setObjectName("pushButton_diagnosis")
        self.pushButton_recipe_detail = QtWidgets.QPushButton(Dialog)
        self.pushButton_recipe_detail.setGeometry(QtCore.QRect(0, 150, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_recipe_detail.setFont(font)
        self.pushButton_recipe_detail.setObjectName("pushButton_recipe_detail")
        self.label_welcome = QtWidgets.QLabel(Dialog)
        self.label_welcome.setGeometry(QtCore.QRect(250, 40, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.pushButton_recipe_master = QtWidgets.QPushButton(Dialog)
        self.pushButton_recipe_master.setGeometry(QtCore.QRect(0, 70, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_recipe_master.setFont(font)
        self.pushButton_recipe_master.setObjectName("pushButton_recipe_master")
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setGeometry(QtCore.QRect(250, 120, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_diagnosis.setText(_translate("Dialog", "就诊"))
        self.pushButton_recipe_detail.setText(_translate("Dialog", "处方药品清单"))
        self.label_welcome.setText(_translate("Dialog", "就诊管理"))
        self.pushButton_recipe_master.setText(_translate("Dialog", "处方"))
        self.pushButton_back.setText(_translate("Dialog", "返回"))
