# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_search_operator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_refresh.setGeometry(QtCore.QRect(510, 0, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_refresh.setFont(font)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(0, 0, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(120, 0, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(-10, 40, 641, 391))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineEdit_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_search.setGeometry(QtCore.QRect(0, 430, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_search.setFont(font)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.pushButton_query = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_query.setGeometry(QtCore.QRect(440, 430, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_query.setFont(font)
        self.pushButton_query.setObjectName("pushButton_query")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_refresh = QtWidgets.QAction(MainWindow)
        self.action_refresh.setObjectName("action_refresh")
        self.action_search = QtWidgets.QAction(MainWindow)
        self.action_search.setObjectName("action_search")
        self.action_back = QtWidgets.QAction(MainWindow)
        self.action_back.setObjectName("action_back")
        self.menu.addAction(self.action_refresh)
        self.menu.addAction(self.action_search)
        self.menu.addSeparator()
        self.menu.addAction(self.action_back)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.action_refresh.triggered.connect(self.pushButton_refresh.click) # type: ignore
        self.action_search.triggered.connect(self.lineEdit_search.setFocus) # type: ignore
        self.action_back.triggered.connect(self.pushButton_back.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_refresh.setText(_translate("MainWindow", "刷新"))
        self.pushButton_back.setText(_translate("MainWindow", "返回上一级"))
        self.label_title.setText(_translate("MainWindow", "test"))
        self.pushButton_query.setText(_translate("MainWindow", "查询"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action_refresh.setText(_translate("MainWindow", "刷新"))
        self.action_search.setText(_translate("MainWindow", "查询"))
        self.action_back.setText(_translate("MainWindow", "返回上一级"))
