# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_user_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 212)
        self.label_welcome = QtWidgets.QLabel(Dialog)
        self.label_welcome.setGeometry(QtCore.QRect(200, 30, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.pushButton_patient = QtWidgets.QPushButton(Dialog)
        self.pushButton_patient.setGeometry(QtCore.QRect(0, 140, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_patient.setFont(font)
        self.pushButton_patient.setObjectName("pushButton_patient")
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setGeometry(QtCore.QRect(210, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_root = QtWidgets.QPushButton(Dialog)
        self.pushButton_root.setGeometry(QtCore.QRect(0, 0, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_root.setFont(font)
        self.pushButton_root.setObjectName("pushButton_root")
        self.pushButton_doctor = QtWidgets.QPushButton(Dialog)
        self.pushButton_doctor.setGeometry(QtCore.QRect(0, 70, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_doctor.setFont(font)
        self.pushButton_doctor.setObjectName("pushButton_doctor")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_welcome.setText(_translate("Dialog", "用户管理"))
        self.pushButton_patient.setText(_translate("Dialog", "患者"))
        self.pushButton_back.setText(_translate("Dialog", "返回"))
        self.pushButton_root.setText(_translate("Dialog", "管理员"))
        self.pushButton_doctor.setText(_translate("Dialog", "医生"))
