# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_admin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 280)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 450, 191))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_username = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_username.setTitle("")
        self.groupBox_username.setObjectName("groupBox_username")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_username)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_username = QtWidgets.QLabel(self.groupBox_username)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.horizontalLayout_14.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(self.groupBox_username)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout_14.addWidget(self.lineEdit_username)
        self.verticalLayout.addWidget(self.groupBox_username)
        self.groupBox_password = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_password.setTitle("")
        self.groupBox_password.setObjectName("groupBox_password")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_password)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_password = QtWidgets.QLabel(self.groupBox_password)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_13.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox_password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_13.addWidget(self.lineEdit_password)
        self.verticalLayout.addWidget(self.groupBox_password)
        self.pushButton_exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(270, 200, 150, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_submit = QtWidgets.QPushButton(Dialog)
        self.pushButton_submit.setGeometry(QtCore.QRect(40, 200, 150, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_username.setText(_translate("Dialog", "用户名"))
        self.label_password.setText(_translate("Dialog", "密码"))
        self.pushButton_exit.setText(_translate("Dialog", "返回"))
        self.pushButton_submit.setText(_translate("Dialog", "提交"))
